sudo: false
language: java
jdk:
- oraclejdk8
branches:
only:
- master
cache:
  directories:
  - $HOME/.m2
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -q
script:  mvn test -B -q
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $DEPLOY_DIR/pubring.gpg.enc -out $DEPLOY_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $DEPLOY_DIR/secring.gpg.enc -out $DEPLOY_DIR/secring.gpg -d
- $DEPLOY_DIR/publish.sh
env:
  global:
  - DEPLOY_DIR="`pwd`/deploy"
  - secure: K5PQkPIAC1xMkzKO0y/jbUxt+A+0M6x8LvmvkQutDITySUs3sMk5wvAn/CrHODOR2m/JGM4W+0FJNZRGfWLr6EEXmsMpEipZ3+d7LThaw/c+SImqb7iZ0Ic0Fj28Tk6nhkHUh7wn6RejJyFEkT3syHVUYUOL2xfvhc0yKYriiPA=
  - secure: NYZKwZAU5uAKHiX7IaFIdCXk+XCOSfc7MSSg86wOLug6YRAYbbxzttplWPsi/zZqc0GL4oDPC/bFhIU6iGhcsgqQqb6yajpsahsX+uDpmWciV/lwV6dIBNUgxGpfIk5R6RlsP+nkHtj6NVCPELz+ixE/W2wVEvDsUf7yUdOKaWk=
  - secure: aXQEwHAEGLrmGwoOQPSsAOHPJTNsp3Er1eddtzjsPBfb8RkB0HZCgwFNVECXkXZtyTMztXKInWVioJSbxLOs7hR9995fhTM9D0/KI41kLGY0NFu6SqRnTwle66N+K9ikP+KEkiWfIgxvqyqf3Lz8XtIc1ZWypbAIldI8+zUmUU8=
  - secure: YKSlR/cBGg0XzOLh/l8OjW54cLGHupvVC59MbI+rMsRMjBUvqGWH32Wp5CbltmHMeB7QyplpwTPSzgYJwmX1PamU6E1Ulbyo0JbS+myz2HpdmAYP1yHoSXkRPs5ll/a5JOu0OM8QI4/GUk9KNyRh9h8kXnu+IKkFUBovFKMw2Rw=
  - secure: D1eK9wcUBkkALVu2NpIU3bdfYU5E9rMM4NiXNbjEmIB+TwA2eBaci9VGHL83O/6+icG2VUhYiTc6Y0HeDSbjfz2tSDK3qXSZIssZEg0uZUM+uq+heNiyi3CGyVD2dVNH1lLKHktn4v6+4oP96dHAuVLwtsH/yvdoFSxM9UaP0sg=
