sudo: false
language: java
jdk:
  - oraclejdk7
branches: 
only:
- master
cache:
  directories:
  - "$HOME/.m2"
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $DEPLOY_DIR/pubring.gpg.enc -out $DEPLOY_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $DEPLOY_DIR/secring.gpg.enc -out $DEPLOY_DIR/secring.gpg -d
- "$DEPLOY_DIR/publish.sh"
env:
  global:
  - DEPLOY_DIR="`pwd`/deploy"
