/**
 * Copyright 2015 Nortal Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and limitations under the
 * License.
 **/

package com.nortal.jroad.wsdl;

import javax.wsdl.Definition;
import javax.wsdl.Part;
import javax.xml.namespace.QName;

import org.springframework.ws.wsdl.wsdl11.provider.SuffixBasedMessagesProvider;

/**
 * X-Road specific implementation of strategy for adding messages to a <code>Definition</code>, whose
 * {@link XRoadMessagesProvider#populatePart(Definition, Part, QName)} creates messages according to schema elements with
 * suffix Request/Response. Used by {@link XTeeWsdlDefinition}.
 * 
 * @author Lauri Lättemäe (lauri.lattemae@nortal.com) - protocol 4.0
 */
// TODO Lauri: maybe we can remove it or we want to remove Request suffix from input names as it seems to be needed by
// xroad doc?
// Probably can drop - The name of the output wrapper element could be (but doesn't have to be) the operation name
// appended with 'Response'.
// Mapping input messages preferred way is not supported at the moment eg. add/addResponse - messages/parts are
// generated by schema element name suffixes and message/operation names are bound to those values
@Deprecated
public class XRoadMessagesProvider extends SuffixBasedMessagesProvider {

}
