//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.23 at 11:57:10 PM EEST
//

package com.nortal.jroad.example.model;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.nortal.jroad.example.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _EchoResponse_QNAME =
      new QName("http://producers.naidis.xtee.riik.ee/producer/naidis", "EchoResponse");
  private final static QName _AttachmentEchoRequest_QNAME =
      new QName("http://producers.naidis.xtee.riik.ee/producer/naidis", "AttachmentEchoRequest");
  private final static QName _EchoRequest_QNAME =
      new QName("http://producers.naidis.xtee.riik.ee/producer/naidis", "EchoRequest");
  private final static QName _AttachmentEchoResponse_QNAME =
      new QName("http://producers.naidis.xtee.riik.ee/producer/naidis", "AttachmentEchoResponse");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * com.nortal.jroad.example.model
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link AttachmentEchoNest }
   */
  public AttachmentEchoNest createAttachmentEchoNest() {
    return new AttachmentEchoNest();
  }

  /**
   * Create an instance of {@link AttachmentEchoRequest }
   */
  public AttachmentEchoRequest createAttachmentEchoRequest() {
    return new AttachmentEchoRequest();
  }

  /**
   * Create an instance of {@link AttachmentEchoResponse }
   */
  public AttachmentEchoResponse createAttachmentEchoResponse() {
    return new AttachmentEchoResponse();
  }

  /**
   * Create an instance of {@link EchoResponse }
   */
  public EchoResponse createEchoResponse() {
    return new EchoResponse();
  }

  /**
   * Create an instance of {@link EchoRequest }
   */
  public EchoRequest createEchoRequest() {
    return new EchoRequest();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link EchoResponse }{@code >}
   */
  @XmlElementDecl(namespace = "http://producers.naidis.xtee.riik.ee/producer/naidis", name = "EchoResponse")
  public JAXBElement<EchoResponse> createEchoResponse(EchoResponse value) {
    return new JAXBElement<EchoResponse>(_EchoResponse_QNAME, EchoResponse.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentEchoRequest }{@code >}
   */
  @XmlElementDecl(namespace = "http://producers.naidis.xtee.riik.ee/producer/naidis", name = "AttachmentEchoRequest")
  public JAXBElement<AttachmentEchoRequest> createAttachmentEchoRequest(AttachmentEchoRequest value) {
    return new JAXBElement<AttachmentEchoRequest>(_AttachmentEchoRequest_QNAME,
                                                  AttachmentEchoRequest.class,
                                                  null,
                                                  value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link EchoRequest }{@code >}
   */
  @XmlElementDecl(namespace = "http://producers.naidis.xtee.riik.ee/producer/naidis", name = "EchoRequest")
  public JAXBElement<EchoRequest> createEchoRequest(EchoRequest value) {
    return new JAXBElement<EchoRequest>(_EchoRequest_QNAME, EchoRequest.class, null, value);
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentEchoResponse }{@code >}
   */
  @XmlElementDecl(namespace = "http://producers.naidis.xtee.riik.ee/producer/naidis", name = "AttachmentEchoResponse")
  public JAXBElement<AttachmentEchoResponse> createAttachmentEchoResponse(AttachmentEchoResponse value) {
    return new JAXBElement<AttachmentEchoResponse>(_AttachmentEchoResponse_QNAME,
                                                   AttachmentEchoResponse.class,
                                                   null,
                                                   value);
  }

}
