//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.09.23 at 11:57:10 PM EEST
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://producers.naidis.xtee.riik.ee/producer/naidis")
package com.nortal.jroad.example.model;

